// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/pack/generator.go

// Package pack is a generated GoMock package.
package pack

import (
	reflect "reflect"

	pack "github.com/becosuke/golang-examples/kvstore/internal/domain/pack"
	gomock "github.com/golang/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockGenerator) GenerateKey() *pack.Key {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateKey")
	ret0, _ := ret[0].(*pack.Key)
	return ret0
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockGeneratorMockRecorder) GenerateKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockGenerator)(nil).GenerateKey))
}
